version: "3.8"

services:
  nodejs:
    build: .
    container_name: yelpcamp-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: yelpcamp-mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
