---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHFxOWF3Nm9hCg==
  CLOUDINARY_KEY: NTY2MTgyNDMzOTY3NTIxCg==
  CLOUDINARY_SECRET: LTNMWVVWSVE2MndHS2ZRRHRCY0U4Q3pRQ3ZnCg==
  MAPBOX_TOKEN: cGsuZXlKMUlqb2ljM0pwYm1sa2FHbHRjaUlzSW1FaU9pSmpiVzEwTVRScWFXa3hhRGRpTW05elpEaDJaakp1TldkMUluMC4tY0NvRGU3Ymo2XzR4MFZJMzdVM0xBCg==
  DB_URL: bW9uZ29kYitzcnY6Ly9zcmluaWRoaW1yMmtfZGJfdXNlcjpTcmluaUBzcmluaWRoaW1yMTAuaGlheHNxcy5tb25nb2RiLm5ldC8/YXBwTmFtZT1TcmluaWRoaW1yMTA=
  SECRET: cnRyMTgwCg==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: srinidhimr/db1-nodejs:v5
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: yelp-camp
  ports:
    - name: http
      port: 3000           # Service port
      targetPort: 3000  # Container port
      nodePort: 30080   # Optional (range 30000–32767)
